import { type Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Dell Latitude 5440 Laptop',
    brand: 'Dell',
    category: 'Laptops',
    image: 'https://placehold.co/400x400.png',
    description: 'A mainstream 14" laptop with intelligent performance and a compact design. Ideal for business professionals who need reliability and productivity.',
    specs: {
      processor: '13th Gen Intel Core i5/i7',
      ram: '8GB/16GB/32GB DDR4',
      storage: '256GB/512GB/1TB NVMe SSD',
      display: '14" FHD (1920x1080) Anti-Glare',
    },
  },
  {
    id: '2',
    name: 'Dell Vostro 3530 Laptop',
    brand: 'Dell',
    category: 'Laptops',
    price: 0,
    image: 'https://placehold.co/400x400.png',
    description: 'A 15.6-inch laptop with the latest Intel® Core™ processors, essential features for small businesses, and a focus on security and connectivity.',
    specs: {
      processor: '13th Gen Intel Core i3/i5/i7',
      ram: '8GB/16GB DDR4',
      storage: '256GB/512GB/1TB NVMe SSD',
      display: '15.6" FHD (1920x1080) Anti-Glare',
    },
  },
  {
    id: '3',
    name: 'Dell Inspiron 15 Laptop',
    brand: 'Dell',
    category: 'Laptops',
    price: 0,
    image: 'https://placehold.co/400x400.png',
    description: 'A versatile 15-inch laptop for everyday use. Enjoy a vibrant display and responsive performance for entertainment, school, and work.',
    specs: {
      processor: 'Intel Core i5/i7 or AMD Ryzen 5/7',
      ram: '8GB/16GB DDR4',
      storage: '256GB/512GB/1TB NVMe SSD',
      display: '15.6" FHD (1920x1080) Touch/Non-Touch',
    },
  },
  {
    id: '4',
    name: 'Dell Latitude 7440 Laptop',
    brand: 'Dell',
    category: 'Laptops',
    price: 0,
    image: 'https://placehold.co/400x400.png',
    description: 'A premium, ultralight 14" business laptop with advanced security features, a stunning QHD+ display option, and long battery life.',
    specs: {
      processor: '13th Gen Intel Core i5/i7 vPro',
      ram: '16GB/32GB LPDDR5',
      storage: '512GB/1TB/2TB NVMe SSD',
      display: '14" FHD+ or QHD+ Anti-Glare, Touch',
    },
  },
    {
    id: '5',
    name: 'Dell Vostro 5630 Laptop',
    brand: 'Dell',
    category: 'Laptops',
    price: 0,
    image: 'https://placehold.co/400x400.png',
    description: 'Experience enhanced performance on a 16-inch laptop with a 16:10 aspect ratio display, 13th Gen Intel® Core™ processors and an NVIDIA® RTX graphics option.',
    specs: {
      processor: '13th Gen Intel Core i5/i7',
      ram: '8GB/16GB LPDDR5',
      storage: '512GB/1TB NVMe SSD',
      display: '16.0" FHD+ (1920 x 1200) Anti-Glare',
    },
  },
  {
    id: '6',
    name: 'Dell Inspiron 16 2-in-1 Laptop',
    brand: 'Dell',
    category: 'Laptops',
    price: 0,
    image: 'https://placehold.co/400x400.png',
    description: 'A flexible 16-inch 2-in-1 with a large display, four different modes, and a built-in stylus for a versatile user experience.',
    specs: {
      processor: 'Intel Core i5/i7 or AMD Ryzen 5/7',
      ram: '8GB/16GB DDR4',
      storage: '512GB/1TB NVMe SSD',
      display: '16" FHD+ (1920 x 1200) Touch Display',
    },
  },
  {
    id: '7',
    name: 'HP EliteBook 840 G10',
    brand: 'HP',
    category: 'Laptops',
    price: 0,
    image: 'https://placehold.co/400x400.png',
    description: 'A premium business laptop with robust security, powerful performance, and a sleek, durable design for the modern professional.',
    specs: {
      processor: '13th Gen Intel Core i5/i7',
      ram: '16GB/32GB DDR5',
      storage: '512GB/1TB NVMe SSD',
      display: '14" WUXGA (1920x1200) IPS',
    },
  },
  {
    id: '8',
    name: 'Lenovo ThinkPad T14s Gen 4',
    brand: 'Lenovo',
    category: 'Laptops',
    price: 0,
    image: 'https://placehold.co/400x400.png',
    description: 'A thin and light business laptop powerhouse with sustainable materials, long battery life, and top-tier performance.',
    specs: {
      processor: 'AMD Ryzen 7 PRO',
      ram: '16GB/32GB LPDDR5x',
      storage: '512GB/1TB NVMe SSD',
      display: '14" WUXGA (1920 x 1200) Low Power IPS',
    },
  },
];

export const testimonials = [
  {
    id: 1,
    name: 'Anil Kumar',
    title: 'CEO, Creative Solutions',
    quote: 'Suchethan Infotech provided us with the perfect workstations for our design team. The service was exceptional and the delivery was prompt. Highly recommended!',
    rating: 5,
  },
  {
    id: 2,
    name: 'Priya Sharma',
    title: 'Freelance Developer',
    quote: 'I bought a Lenovo ThinkPad and it\'s been a fantastic machine. The team helped me choose the right specs for my coding needs. Great pricing and expert advice.',
    rating: 5,
  },
  {
    id: 3,
    name: 'Rajesh Singh',
    title: 'IT Manager, Alpha Corp',
    quote: 'Their Annual Maintenance Contract is a lifesaver. Fast, reliable service that keeps our office systems running without a hitch. The peace of mind is invaluable.',
    rating: 4,
  },
];
