import { type Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Dell XPS 15',
    brand: 'Dell',
    category: 'Laptops',
    price: 1899.99,
    image: 'https://placehold.co/400x400.png',
    description: 'A premium laptop with stunning visuals and powerful performance.',
    specs: {
      processor: 'Intel Core i7',
      ram: '16GB DDR5',
      storage: '512GB NVMe SSD',
      display: '15.6" 4K UHD+ Touch',
    },
  },
  {
    id: '2',
    name: 'Lenovo ThinkPad X1 Carbon',
    brand: 'Lenovo',
    category: 'Laptops',
    price: 1649.0,
    image: 'https://placehold.co/400x400.png',
    description: 'Ultralight. Ultrapowerful. Ultra-no-brainer.',
    specs: {
      processor: 'Intel Core i7',
      ram: '16GB LPDDR5',
      storage: '1TB NVMe SSD',
      display: '14" WQHD IPS',
    },
  },
  {
    id: '3',
    name: 'HP Spectre x360',
    brand: 'HP',
    category: 'Laptops',
    price: 1399.99,
    image: 'https://placehold.co/400x400.png',
    description: 'A versatile 2-in-1 laptop with a sleek design and premium features.',
    specs: {
      processor: 'Intel Core i7',
      ram: '16GB DDR4',
      storage: '512GB NVMe SSD',
      display: '13.5" WUXGA+ Touch',
    },
  },
  {
    id: '4',
    name: 'Dell Alienware Aurora R15',
    brand: 'Dell',
    category: 'Desktops',
    price: 2499.99,
    image: 'https://placehold.co/400x400.png',
    description: 'A gaming desktop with elite-level performance and iconic design.',
    specs: {
      processor: 'Intel Core i9',
      ram: '32GB DDR5',
      storage: '1TB SSD + 2TB HDD',
    },
  },
  {
    id: '5',
    name: 'Lenovo Legion Tower 5i',
    brand: 'Lenovo',
    category: 'Desktops',
    price: 1499.99,
    image: 'https://placehold.co/400x400.png',
    description: 'Dominate the competition with this powerful and stylish gaming rig.',
    specs: {
      processor: 'Intel Core i7',
      ram: '16GB DDR5',
      storage: '1TB NVMe SSD',
    },
  },
  {
    id: '6',
    name: 'HP OMEN 45L',
    brand: 'HP',
    category: 'Desktops',
    price: 2199.99,
    image: 'https://placehold.co/400x400.png',
    description: 'Engineered for extreme performance with a revolutionary cooling system.',
    specs: {
      processor: 'AMD Ryzen 9',
      ram: '32GB DDR4',
      storage: '1TB NVMe SSD',
    },
  },
  {
    id: '7',
    name: 'Dell Precision 5820 Tower',
    brand: 'Dell',
    category: 'Workstations',
    price: 2899.0,
    image: 'https://placehold.co/400x400.png',
    description: 'A powerful and scalable workstation for professional creators.',
    specs: {
      processor: 'Intel Xeon W',
      ram: '64GB DDR4 ECC',
      storage: '2TB NVMe SSD',
    },
  },
  {
    id: '8',
    name: 'Logitech MX Master 3S',
    brand: 'Other',
    category: 'Accessories',
    price: 99.99,
    image: 'https://placehold.co/400x400.png',
    description: 'An iconic mouse, remastered for performance and ergonomics.',
    specs: {},
  },
];

export const testimonials = [
  {
    id: 1,
    name: 'Anil Kumar',
    title: 'CEO, Creative Solutions',
    quote: 'Suchethan Infotech provided us with the perfect workstations for our design team. The service was exceptional and the delivery was prompt. Highly recommended!',
    rating: 5,
  },
  {
    id: 2,
    name: 'Priya Sharma',
    title: 'Freelance Developer',
    quote: 'I bought a Lenovo ThinkPad and it\'s been a fantastic machine. The team helped me choose the right specs for my coding needs. Great pricing and expert advice.',
    rating: 5,
  },
  {
    id: 3,
    name: 'Rajesh Singh',
    title: 'IT Manager, Alpha Corp',
    quote: 'Their Annual Maintenance Contract is a lifesaver. Fast, reliable service that keeps our office systems running without a hitch. The peace of mind is invaluable.',
    rating: 4,
  },
];
